### PR TITLE
add email template

### PR DESCRIPTION
**Pull request by maelle**
cc @awalsh17 -- thanks again! I was wondering what email subject you use for such emails?

### CODE REVIEW

**Comment by maelle** [comment]
Preview https://deploy-preview-24--r-ladies-guide.netlify.app/organization/intro/expenses/

**Comment by awalsh17** [comment]
Hi @maelle - Looks good! I think we tend to customize the subject line. It would be good to hear other ideas about a subject line that does not sound like spam. We might use, "Data science group for R enthusiasts," "Hosting an R-Ladies meetup," or "Introducing R-Ladies Philadelphia!".

**Comment by maelle** [comment]
Thanks! Do you think a more explicit subject could work e.g. "Partner with R-Ladies Philadelphia"? :thinking:

**Comment by maelle** [comment]
I added a few points about the subject, we can revisit later if we get better ideas. Thanks again for the template and your feedback!

**Pull request merged**
