### PR TITLE
feat: display last modification date on each page

### LINKED ISSUE #145: last updated information
Should we indicate when information on the guide was last updated somehow?

Some ideas:

1. `NEWS.md` that tracks updated changes moving forward
2. a tip box that gets added to each index when updated that autmatically pulls in the date of update.

Something else?

### PR DESCRIPTION
**Pull request by maelle**
Fix #145

It's a bit too much at the moment, maybe only bold would be enough?

image

### CODE REVIEW

**Comment by shannonpileggi** [comment]
oooh i love it @maelle, looks great!

fyi @rivaquiroga @yabellini

**Comment by shannonpileggi** [comment]
that is so slick with just a few lines of code! 🥳

**Comment by rivaquiroga** [comment]
Looks great!

**Comment by maelle** [comment]
> Welcome maelle! It looks like this is your first contribution to this repository. 

:joy_cat: 

I'll wait for Yani's ok.

**Comment by drmowinckels** [comment]
> > Welcome maelle! It looks like this is your first contribution to this repository.
> 
> 😹
> 
> I'll wait for Yani's ok.

yeah, ok... so that action seems to not understand who are new contributors :P

**Comment by yabellini** [comment]
Love it!! Thanks @maelle 🙏

**Review by shannonpileggi — APPROVED** [review]

**Pull request merged**
